### ISSUE TITLE
Add option to generate smart quotes

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/metanorma-standoc#11]
Smart quotes are not currently being generated in the XML, HTML, DOC output, though that is the default of native asciidoctor. That is presumably because the metanorma asciidoctor conversion code is preempting the operation of some Asciidoctor substitutions, though "--" is being converted to em-dash fine.

Do we want the option of smart quotes? And which default value do we want, on or off?

**Comment by ronaldtse** [comment]
Yes it would be a good option, default to on.

**Comment by opoudjis** [comment]
Native Asciidoctor: dumb quotes are " ', and smart quotes are "` `" '` `'; smart apostrophe is ' and dumb apostrophe is \'.

https://github.com/asciidoctor/asciidoctor/issues/725 proposed six years ago a `:smartquotes:` mode, like what is being proposed here.

https://github.com/pbhogan/sterile is already being used to smart-format the XML received from bibliographic entries online. Enabling the `:smartquotes:` mode will trigger Sterile smart format on the contents of the XML, with the exception of sourcecode, pre, tt. If you ever need to use dumb quotes, you should not be using `:smartquotes:`.

The rules of Sterile smart format are given as regexen in https://github.com/pbhogan/sterile/blob/master/lib/sterile/data/smart_format_rules.rb

**Comment by ronaldtse** [comment]
Sounds good, as long as we have this documented. Thanks!
