### ISSUE TITLE
Read document-class from Document preamble

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-standoc#23]
We should define a "document preamble" that we can encode metadata of the Metanorma document.

Currently, we require the following command to build a CSD document:

```
metanorma -t csd -x html csd-my-document.adoc
```

The problem happens when there are multiple document classes in the same directory; a `Makefile` is unable to differentiate the different documents, for example, an ISO document vs a CSD document.

The solution is to keep the `-t` and `-x` commands inside the document itself (as part of its "metanorma directives"), so that an `iso-document.adoc` and `csd-document.adoc` can create their own type of documents.

For example, this document is built using the ISO class processor.

```
= My ISO document
:mn-document-class: iso
:mn-output-extensions: html,xml,pdf

.Foreword
...
```

**Comment by opoudjis** [comment]
I will not be dropping the -t and -x options from metanorma-cli, and this functionality does not make operational sense. (If you are dumping ISO and CSD documents in the same directory indiscrimately, you have an information management problem.)

**Comment by ronaldtse** [comment]
We're going to make those optional if they are defined in the doc-attributes. 

> (If you are dumping ISO and CSD documents in the same directory indiscrimately, you have an information management problem.)

Yes, and it is a way to solve this. It is unreasonable to expect people to create different directories for multiple documents. (and run different commands for different documents)

**Comment by ronaldtse** [comment]
> We're going to make those optional if they are defined in the doc-attributes.

And this behavior is exactly like how asciidoctor-cli behaves, anyway.

**Comment by opoudjis** [comment]
Implemented in metanorma and metanorma-cli.
