### ISSUE TITLE
URGENT: rfc-editor.org is down and all documents that uses ietfbib not compilable

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-standoc#27]
From Thomas (and I also encountered this):

> it stopped working as www.rfc-editor.org:443 is not available anymore and the domain went into an domain selling phase ☹

```  
make clean all
rm -f csd-vpoll.xml csd-vpoll.pdf csd-vpoll.html
if [ "x" == "1x" ]; then bundle; fi
FILENAME=csd-vpoll.adoc; \
       echo "Compiling via docker..."; docker run -v "$(pwd)":/metanorma/ ribose/metanorma "metanorma -t csd -x xml,pdf,html $FILENAME"
Compiling via docker...
asciidoctor: WARNING: gem 'concurrent-ruby' is not installed. This gem is recommended when registering custom converters.
[metanorma] detecting backends:
[metanorma] processor "rfc2" registered
[metanorma] processor "rfc3" registered
[metanorma] processor "standoc" registered
[metanorma] processor "iso" registered
/usr/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect': Failed to open TCP connection to www.rfc-editor.org:443 (Connection refused - connect(2) for "www.rfc-editor.org" port 443) (Errno::ECONNREFUSED)
```

Point is, bib fetch failure should not cause the document to not compile.

**Comment by opoudjis** [comment]
Easy fix, which I'll also put in the other gems: put a rescue around the fetch.

**Comment by ronaldtse** [comment]
Thanks @opoudjis -- just want to make sure the RESCUE will be announced to the user (and maybe in the text) so the user won't see a reference missing, and knows how to recover from it. Maybe a new ticket?

**Comment by ArtlessAptyrex** [comment]
There is a ticket in the IETF fault queue, but the ticket server is just sending empty pages ... sigh! Tkt number is 245240, lodged on 2018-11-29. Meanwhile, you can get RFCs from IETF directly.

  "To go directly to a text version of an RFC, type https://www.ietf.org/rfc/rfcNNNN.txt into the location field of your browser, where NNNN is the RFC number. "

**Comment by ronaldtse** [comment]
Thanks for the tip @ArtlessAptyrex ! In addition we could also switch to using `https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.nnnn.xml` instead.

I'm not sure why we used the rfc-editor.org site since it has always been rather slow...

**Comment by opoudjis** [comment]
> e.g. if , _third_ was missing (comma and those after), then the citation becomes funny

Indeed, that is currently the case, Metanorma Asciidoc requires there to be a title. If you'd like the title to be optional, you can request a new ticket. On the other hand, requiring a title is exactly what you need for graceful recovery like we're discussing here; so I'd rather we keep requiring it.

**Comment by ronaldtse** [comment]
The issue with requiring “third” is that when a citation is autofetched, I need to put in some random title like “AUTOFILL”. Once it has been fetched (and cache present), that becomes useless.

**Comment by ArtlessAptyrex** [comment]
The correct URL for xml rfcs is: https://xml2rfc.tools.ietf.org/public/rfc/xml/rfcNNNN.xml.
The lowest number in the directory is rfc2000.xml, the highest is rfc5322.xml. There are just 440 rfc's in the directory.

Note that the public directory is browsable. Just plug https://xml2rfc.tools.ietf.org/public<https://xml2rfc.tools.ietf.org/public/rfc/xml/> into your browser.
There is an empty txt subdirectory, and an html directory that also has a bunch of RFCs


-- Russell Page.


Dona nobis pacem.

________________________________

**Comment by opoudjis** [comment]
Caches can be deleted, files can be transferred without the cache, files can be born offline. We should keep the title.

**Comment by ronaldtse** [comment]
@ArtlessAptyrex , the URL https://xml2rfc.tools.ietf.org/public/rfc/bibxml/reference.RFC.nnnn.xml provides BibXML which is bibliographic information, while https://xml2rfc.tools.ietf.org/public/rfc/xml/rfcNNNN.xml is about RFC XML. 

In the context of this gem, we are seeking only the bibliographic information (and the link contains all of them. Thanks!
