### ISSUE TITLE
Use "=" for title if “:title:” document attribute is omitted

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-standoc#29]
Originally we used a separate `:title-xxx:` because ISO documents have a multi-part title.

In document classes that don't have a multipart title, like CSD, OGC or RFC, we don't need a multi-part title, and the normal Asciidoctor `=` title suffices.

This issue is to allow reading the `:title:` attribute from the Asciidoc `=` line for document classes that don't need multi-part titles.

Beware that we will still need to support multi-lingual titles. This should work:

```adoc
= English title
:title-fr: titre francais
```

As should this:

```adoc
= Blah
:title: English title
:title-fr: titre francais
```

**Comment by opoudjis** [comment]
Except that I don't think we support multilingual titles anywhere you haven't explicitly asked for it (which is ISO and GB). I'll take the opportunity to parse `:title-XX:` as a foreign-language title
