### ISSUE TITLE
Bibliographic date for "revision" is outside of Bibdata structure

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-standoc#30]
In Metanorma XML we have the revision date outside of the `<bibdata>` structure:

```xml
<version>
  <edition>1</edition>
  <revision-date>2018-09-10T00:00:00Z</revision-date>
</version>
```

This makes it impossible to know the revision (and other dates) of a document from the Relaton file, we need the Metanorma file to do that.

Should this information be available within `<bibdata>`?

**Comment by opoudjis** [comment]
We left it outside of the bibdata out of a notion that the bibdata was describing the work and not the version. But that is overly scrupulous, I agree. Moving the version back into bibdata is going to require a lot of code changes.

I don't even remember where the relaton writeup is, but it is going to have to be updated in light of these changes.

**Comment by ronaldtse** [comment]
The write up is at relaton-models. I believe we have bibdates within bibdata.

**Comment by opoudjis** [comment]
We do, but the revision date should be kept separate; it does not correspond to a distinct phase of document production, but applies across any of them.

**Comment by ronaldtse** [comment]
Maybe what we need is to encode the revision dates in both — inside bibdata (the publication date) and also outside of it (as the generation date of document). 

At the CalConnect standards repository we’re trying to make a page for each project like the ISO site, so if we can represent a Relaton object with multiple document revisions (at different stages), we can generate a page that show standards progression and also the drafts that come with each stage.

**Comment by opoudjis** [comment]
If it's the publication date of the document, it's covered by the existing `<date type="published">`. Revision dates apply to pre-published documents; and publication dates of different editions should be covered as distinct related relaton descriptions. No, it's going to be simpler just to move the version tag inside bibdata.

The writeup is in fact in the ISO690 document. That document is going to have to be updated extensively.

**Comment by opoudjis** [comment]
The representation of multiple document revisions in a single Relaton file is covered by https://github.com/riboseinc/relaton/issues/19

**Comment by opoudjis** [comment]
Following https://github.com/riboseinc/metanorma-model-iso/issues/15#issuecomment-364794094, edition is now in bibdata as a separate tag, and should be removed from the version tag.
