### ISSUE TITLE
Support authorship and affiliations

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-standoc#32]
We need to support affiliations in order to model IETF documents. Ideally we want to do that in CSD as well. This is why we modeled them in Relaton. 

The way forward could be using the same/similar document attributes as in AsciiRFC. 

From: https://github.com/riboseinc/metanorma-model-ogc/issues/2#issuecomment-446030449

**Comment by opoudjis** [comment]
Duplicates https://github.com/riboseinc/metanorma-csd/issues/71
