### ISSUE TITLE
Issue with italics split across lines

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-standoc#39]
The following snippet renders like this:

```adoc
_Physical noise
sources_
```

Becomes
![screen shot 2019-01-07 at 9 09 30 pm](https://user-images.githubusercontent.com/11865/50769940-87084e00-12c0-11e9-9fcb-6a8c68054c38.png)

**Comment by opoudjis** [comment]
Nokogiri postprocessing routine noko() strips all carriage returns from the results of XML Builder. Carriage returns need to be replaced with a single space.
