### ISSUE TITLE
`<sourcecode>` block must indicate type of language

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-standoc#42]
In CSD, this input:

```adoc
[source,java]
----
public class Fibonacci {
    public static long fibonacci(int n) {
        if (n <= 1) return n;
        else return fibonacci(n-1) + fibonacci(n-2);
    }

    public static void main(String[] args) {
        int n = Integer.parseInt(args[0]);
        for (int i = 1; i <= n; i++)
            StdOut.println(i + ": " + fibonacci(i));
    }
}
----
```

Was rendered as this XML:

```xml
<sourcecode id="_efd291ff-701e-4c5d-b922-98018fce71a0">public class Fibonacci { 
    public static long fibonacci(int n) { 
        if (n &lt;= 1) return n; 
        else return fibonacci(n-1) + fibonacci(n-2); 
    } 
 
    public static void main(String[] args) { 
        int n = Integer.parseInt(args[0]); 
        for (int i = 1; i &lt;= n; i++) 
            StdOut.println(i + ": " + fibonacci(i)); 
    } 
}</sourcecode>
```

In the HTML, we should provide rendering for it too. Word rendering maybe a separate task.

**Comment by ronaldtse** [comment]
In addition, there's a bug in here -- `sourcecode` content should be faithful to input and NOT be HTML escaped (see `&lt;`).

**Comment by opoudjis** [comment]
I do not understand what this ticket is asking for. The source code is already rendered in HTML. Is this about highlighting? But you haven't even supplied the programming language in the example.

**Comment by ronaldtse** [comment]
Ah, I was confused. In any case, we need to provide a method to extract `<sourcecode>` blocks from a Metanorma XML. In the XML, we should supply the type of language too.

**Comment by opoudjis** [comment]
Yes, to language type. For extraction, will be a trivial script; I assume it will be part of the Metanorma CLI?

**Comment by opoudjis** [comment]
So, three requirements: language attribute; source code highlighting; and extracting source code in metanorma, as is also to be done for requirements? Your wording is not clear.

**Comment by opoudjis** [comment]
I'm implementing the language attribute, it's needed anyway for requirements.

**Comment by ronaldtse** [comment]
> So, three requirements: language attribute; source code highlighting; and extracting source code in metanorma, as is also to be done for requirements? Your wording is not clear.

Yes.

The language attribute should be back-ported to the Metanorma BasicDoc model too.

**Comment by ronaldtse** [comment]
Oh you already did! 👍 
https://github.com/riboseinc/basicdoc-models/commit/1860d9cf1e5f252a2c01d06180eef35451a96a23

**Comment by opoudjis** [comment]
Used highlightjs to hightlight sourcecode in HTML output. 

Forced output of liquid template to replace `&lt; &gt; &amp;` with `&#x3c; &#x3e; &#x26;`: for some reason those escapes were being ignored when reparsed into Nokogiri for further postprocessing in HTML. For whatever reason, this does not impact Word output.

**Comment by opoudjis** [comment]
Added extraction mode to metanorma. The filenames of the extracted sourcecode fragments are currently unsuffixed numbers in a nominated directory.

**Comment by ronaldtse** [comment]
Thanks @opoudjis !
