### ISSUE TITLE
Option to disable global cache

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-standoc#7]
Skipping global cache is a genuine requirement:

* We often want to also version control the local cache located in the local directory. Just like "Gemfile.lock".

* In the https://github.com/riboseinc/metanorma-docker[Metanorma docker container], we don't want to share global cache but only local cache (in the local directory)

**Comment by opoudjis** [comment]
Done with  `:local-cache-only:` document attribute.

**Comment by ronaldtse** [comment]
@opoudjis thanks — could you also help update the README in metanorma-docker to use this option? Thanks!

**Comment by opoudjis** [comment]
I have. But you've made an assumption that needed to be corrected. The local cache, as you required it, is a separate instance for each file: there is no single `./.relaton.bib.pstore` for all files, but one `./{document-name}.relaton.bib.pstore` for each document.

**Comment by ronaldtse** [comment]
Hah, glad that my assumption was faulty. Thanks @opoudjis !

(the next step is to convert the pstore into something portable and text-based...
