### ISSUE TITLE
Replace `system` calls

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-standoc#8]
https://github.com/riboseinc/metanorma-standoc/search?q=system&unscoped_q=system

**Comment by opoudjis** [comment]
`system "metanorma -t iso test.adoc`

or

`system "cd spec/examples; rm -f rice.xml; rm -f rice.doc; rm -f rice.html; rm -f rice_alt.html; asciidoctor --trace -b iso -r 'metanorma-iso' rice.adoc; cd ../.."`

**Comment by opoudjis** [comment]
Done all other system calls.

**Comment by ronaldtse** [comment]
`system "metanorma -t iso test.adoc` is this supposed to be a test for Metanorma ISO?

For this one:
```
system "cd spec/examples; rm -f rice.xml; rm -f rice.doc; rm -f rice.html; rm -f rice_alt.html; asciidoctor --trace -b iso -r 'metanorma-iso' rice.adoc; cd ../.."
```

Can we only have `asciidoctor --trace -b iso -r 'metanorma-iso' rice.adoc` in `system`? The rest should be FileUtils.  Thanks!

**Comment by opoudjis** [comment]
> `system "metanorma -t iso test.adoc` is this supposed to be a test for Metanorma ISO?

Yes, because I am testing the local Metanorma library call to Metanorma::Iso::Processor

>> `system "cd spec/examples; rm -f rice.xml; rm -f rice.doc; rm -f rice.html; rm -f rice_alt.html; asciidoctor --trace -b iso -r 'metanorma-iso' rice.adoc; cd ../.."`

> Can we only have asciidoctor --trace -b iso -r 'metanorma-iso' rice.adoc in system? The rest should be FileUtils. Thanks!

I have already done that: the rm statements throughout are now FileUtils.

**Comment by ronaldtse** [comment]
Thanks @opoudjis ! In fact, could we change this line:
```
asciidoctor --trace -b iso -r 'metanorma-iso' rice.adoc
```

To:
```ruby
::Asciidoctor.convert_file infile, input_opts
```

As used in https://github.com/asciidoctor/asciidoctor/blob/d15bc65a942a8d3b186eab6e038bfc000c4d48f5/lib/asciidoctor/cli/invoker.rb ?

Since we are not dependent on Asciidoctor's CLI we don't want to go through it in specs too.

**Comment by opoudjis** [comment]
I thought it would be useful to include one CLI call in the specs, but I'm not committed to it. I will reopen this ticket to remove them globally.

**Comment by ronaldtse** [comment]
Thanks @opoudjis! Look forward to consolidating our CLI stuff too.

**Comment by opoudjis** [comment]
Done
